import docs from '@/pages/docs/paths';

export const paths = {
  docs,
  auth: {
    root: '/auth',
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    otp: '/auth/otp',
    terms: '/auth/terms',
    privacy: '/auth/privacy',
  },

  dashboard: {
    root: '/dashboard',
    home: '/dashboard/home',
    management: {
      root: '/dashboard/management',
      customers: {
        root: '/dashboard/management/customers',
        list: '/dashboard/management/customers/list',
        view: (customerId: string) => `/dashboard/management/customers/${customerId}`,
      },
    },
    apps: {
      root: '/dashboard/apps',
      kanban: '/dashboard/apps/kanban',
    },
    widgets: {
      root: '/dashboard/widgets',
      metrics: '/dashboard/widgets/metrics',
      charts: '/dashboard/widgets/charts',
      tables: '/dashboard/widgets/tables',
      applicationUi: {
        coreUi: '/dashboard/widgets/application-ui/core-ui',
        authentication: '/dashboard/widgets/application-ui/authentication',
        forms: '/dashboard/widgets/application-ui/forms',
        overlays: '/dashboard/widgets/application-ui/overlays',
        navigation: '/dashboard/widgets/application-ui/navigation',
        feedback: '/dashboard/widgets/application-ui/feedback',
        dataDisplay: '/dashboard/widgets/application-ui/data-display',
        navbars: '/dashboard/widgets/application-ui/navbars',
        headers: '/dashboard/widgets/application-ui/headers',
        footers: '/dashboard/widgets/application-ui/footers',
        grids: '/dashboard/widgets/application-ui/grids',
        userInfo: '/dashboard/widgets/application-ui/user-info',
        inputs: '/dashboard/widgets/application-ui/inputs',
        buttons: '/dashboard/widgets/application-ui/buttons',
        sliders: '/dashboard/widgets/application-ui/sliders',
        dropzones: '/dashboard/widgets/application-ui/dropzones',
        applicationCards: '/dashboard/widgets/application-ui/application-cards',
        stats: '/dashboard/widgets/application-ui/stats',
        tables: '/dashboard/widgets/application-ui/tables',
        dragDrop: '/dashboard/widgets/application-ui/drag-drop',
        carousels: '/dashboard/widgets/application-ui/carousels',
      },
      pageSections: {
        hero: '/dashboard/widgets/page-sections/hero',
        features: '/dashboard/widgets/page-sections/features',
        pricing: '/dashboard/widgets/page-sections/pricing',
        contact: '/dashboard/widgets/page-sections/contact',
        faq: '/dashboard/widgets/page-sections/faq',
        footers: '/dashboard/widgets/page-sections/footers',
        authentication: '/dashboard/widgets/page-sections/authentication',
        errorPages: '/dashboard/widgets/page-sections/error-pages',
        banners: '/dashboard/widgets/page-sections/banners',
      },
      blogUi: {
        articleCards: '/dashboard/widgets/blog-ui/article-cards',
        comments: '/dashboard/widgets/blog-ui/comments',
        layouts: '/dashboard/widgets/blog-ui/layouts',
        authors: '/dashboard/widgets/blog-ui/authors',
        tableOfContents: '/dashboard/widgets/blog-ui/table-of-contents',
      },
    },
  },
};
